name: "e5_model_small"
platform: "onnxruntime_onnx"

max_batch_size: 4

dynamic_batching {
  preferred_batch_size: [2, 4]
  max_queue_delay_microseconds: 100000
}

input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [512]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [512]
  }
]
output [
  {
    name: "text_emb"
    data_type: TYPE_FP32
    dims: [-1]
  }
]
