name: "concatenate_embedding"
backend: "python"

max_batch_size: 4

dynamic_batching {
  preferred_batch_size: [2, 4]
  max_queue_delay_microseconds: 100000
}

input [
  {
    name: "text_emb"
    data_type: TYPE_FP32
    dims: [384]
  },
  {
    name: "image_emb"
    data_type: TYPE_FP32
    dims: [512]
  }
]

output [
  {
    name: "concatenate_emb"
    data_type: TYPE_FP32
    dims: [-1]
  }
]