stages:
  - build
  - lint
  - test
  - deploy

cache:
  paths:
    - ~/.cache/pip

build-job:
  stage: build
  script:
    - pip install -r requirements.txt


lint-pylint:
  stage: lint
  script:
    - echo "Running pylint..."
    - pip install pylint
    - pylint . || exit 1
    - echo "pylint passed."

lint-ruff:
  stage: lint
  script:
    - echo "Running ruff..."
    - pip install ruff
    - ruff check .
    - echo "ruff passed."

unit-tests:
  stage: test
  script:
    - echo "Running unit tests..."
    - pip install pytest python-slugify
    - PYTHONPATH=$(pwd) pytest tests/tests.py
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
