stages:
  - build
  - lint
  - test
  - deploy

cache:
  paths:
    - ~/.cache/pip

build-job:
  stage: build
  script:
    - pip install -r requirements.txt

lint-pylint:
  stage: lint
  script:
    - echo "Running pylint..."
    - pip install pylint
    - pylint . || exit 1
    - echo "pylint passed."
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

lint-ruff:
  stage: lint
  script:
    - echo "Running ruff..."
    - pip install ruff
    - ruff check .
    - echo "ruff passed."
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

unit-tests:
  stage: test
  script:
    - echo "Running unit tests..."
    - pip install pytest python-slugify
    - PYTHONPATH=$(pwd) pytest tests/tests.py
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'

