services:
  mlflow_db:
    restart: always
    image: pgautoupgrade/pgautoupgrade:13-alpine
    environment:
      POSTGRES_USER: ${MLFLOW_PG_USER}
      POSTGRES_PASSWORD: ${MLFLOW_PG_PASSWORD}
      POSTGRES_DB: ${MLFLOW_PG_DATABASE}
    volumes:
      - mlflow_db_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready", "-p", "5432", "-U", "${MLFLOW_PG_USER}", "-d", "${MLFLOW_PG_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 3

  mlflow:
    image: mlflow_image
    build:
      context: ./mlflow
    depends_on:
      mlflow_db:
        condition: service_healthy
    ports:
      - "${MLFLOW_PORT}:5000"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
    command: >
      mlflow server
      --backend-store-uri postgresql://${MLFLOW_PG_USER}:${MLFLOW_PG_PASSWORD}@mlflow_db:5432/${MLFLOW_PG_DATABASE}
      --host 0.0.0.0
      --serve-artifacts
      --artifacts-destination s3://${MLFLOW_BUCKET_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3


  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  model_service_api:
    image: project_image
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${MODEL_SERVICE_API_PORT}:8001"
    depends_on:
      - redis
      - mlflow
    volumes:
      - .:/app
    command: uvicorn model_service_api:app --host 0.0.0.0 --port 8001

  business_service_api:
    image: project_image
    restart: always
    ports:
      - "${BUSINESS_SERVICE_API_PORT}:8002"
    depends_on:
      - redis
      - model_service_api
    volumes:
      - .:/app
    command: uvicorn business_service_api:app --host 0.0.0.0 --port 8002

volumes:
  mlflow_db_data: