services:
#  db:
#    image: pgautoupgrade/pgautoupgrade:13-alpine
#    container_name: label_studio_db
#    hostname: db
#    environment:
#      - POSTGRES_HOST_AUTH_METHOD=trust
#    volumes:
#      - ./data/postgres-data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-p", "5432", "-U", "postgres", "-d", "postgres" ]
#      interval: 5s
#      timeout: 5s
#      retries: 3
#
#  label_studio:
#    image: heartexlabs/label-studio:latest
#    container_name: label_studio
#    restart: always
#    ports:
#      - "${LABEL_STUDIO_PORT}:8080"
#    volumes:
#      - ./data/label-studio-data:/label-studio/data
#    command:
#      - label-studio
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      - DJANGO_DB=default
#      - POSTGRE_NAME=postgres
#      - POSTGRE_USER=postgres
#      - POSTGRE_PASSWORD=
#      - POSTGRE_PORT=5432
#      - POSTGRE_HOST=db
#
#  minio:
#    image: minio/minio:latest
#    container_name: label_studio_s3
#    restart: always
#    command: server --console-address ":9001" /data/
#    ports:
#      - "${MINIO_WEB_PORT}:9000" # web
#      - "${MINIO_API_PORT}:9001" # api
#    env_file:
#      - .env
#    environment:
#      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
#      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
#    volumes:
#      - ./s3_data:/data
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
#      interval: 30s
#      timeout: 20s
#      retries: 3

  redis:
    image: redis:7-alpine
    container_name: api_cache
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: search_api
    restart: always
    ports:
      - "${API_PORT}:8000"
    command: uvicorn run_api:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
