[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ml_product_categorizer"
version = "0.0.1"
description = "Product categorizer by url"
authors = [
    { name = "Ivan Tikhonov" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.12"


[tool.ruff]
exclude = [
    "venv",
    ".venv",
    ".vscode",
    ".idea",
    ".git",
    ".ipynb",
    ".ipynb_checkpoints",
    "__pycache__",
    "*.ipynb",
    "triton"
]
line-length = 88
indent-width = 4

[tool.ruff.format]
exclude = ["*.pyi"]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    "W",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    "N",
    "S",
    "A",
    "N", # pep8-naming
    "Q", # flake8-quotes
    "ANN", # flake8-annotations
]
ignore = ["B008", "ANN201", "ANN001", "UP007", "N806", "SIM117"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"