name: "image_preprocessor"
backend: "python"
max_batch_size: 64

input [
  {
    name: "raw_image"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "pixel_values"
    data_type: TYPE_FP32
    dims: [3, 224, 224 ]
  }
]