import os

from dotenv import load_dotenv

load_dotenv()


class Settings:
    API_TITLE = os.getenv("API_TITLE")
    API_DESCRIPTION = os.getenv("API_DESCRIPTION")
    API_VERSION = os.getenv("API_VERSION")
    PROJECT_VERSION = os.getenv("PROJECT_VERSION")

    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    S3_ENDPOINT_URL = os.getenv("S3_ENDPOINT_URL")
    BUCKET_NAME = os.getenv("BUCKET_NAME")

    MLFLOW_PORT = os.getenv("MLFLOW_PORT")
    MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI")
    TRACKING_COMMIT_FILE = "tracking_commit.lock"

    SERVICE_MODEL_API = os.getenv("SERVICE_MODEL_API")

    MODEL_SERVICE_API_TITLE = os.getenv("MODEL_SERVICE_API_TITLE")
    MODEL_SERVICE_API_DESCRIPTION = os.getenv("MODEL_SERVICE_API_DESCRIPTION")
    MODEL_SERVICE_API_VERSION = os.getenv("MODEL_SERVICE_API_VERSION")

    BUSINESS_SERVICE_API_TITLE = os.getenv("BUSINESS_SERVICE_API_TITLE")
    BUSINESS_SERVICE_API_DESCRIPTION = os.getenv("BUSINESS_SERVICE_API_DESCRIPTION")
    BUSINESS_SERVICE_API_VERSION = os.getenv("BUSINESS_SERVICE_API_VERSION")
