name: "ensemble"
platform: "ensemble"
max_batch_size: 4

version_policy:{ latest:{ num_versions:1 }}

input [
  { name: "raw_image" data_type: TYPE_STRING dims: [ -1 ] },
  { name: "raw_text"  data_type: TYPE_STRING dims: [ -1 ] }
]

output [
  { name: "concatenate_emb"  data_type: TYPE_FP32 dims: [-1] }
]

ensemble_scheduling {
  step [
    {
      model_name: "image_preprocessor"
      model_version: 1
      input_map  { key: "raw_image" value: "raw_image" }
      output_map { key: "pixel_values" value: "pixel_values" }
    },
    {
      model_name: "text_preprocessor"
      model_version: 1
      input_map  { key: "raw_text" value: "raw_text" }
      output_map { key: "input_ids"      value: "input_ids" }
      output_map { key: "attention_mask" value: "attention_mask" }
    },
    {
      model_name: "clip_model"
      model_version: 1
      input_map  { key: "pixel_values" value: "pixel_values" }
      output_map { key: "image_emb"     value: "image_emb" }
    },
    {
      model_name: "e5_model_small"
      model_version: 1
      input_map  { key: "input_ids"      value: "input_ids" }
      input_map  { key: "attention_mask" value: "attention_mask" }
      output_map { key: "text_emb"       value: "text_emb" }
    },
    {
      model_name: "concatenate_embedding"
      model_version: 1
      input_map  { key: "image_emb"      value: "image_emb" }
      input_map  { key: "text_emb" value: "text_emb" }
      output_map { key: "concatenate_emb"   value: "concatenate_emb" }
    }

  ]
}