ARG BASE_IMAGE=python:3.12-slim
FROM $BASE_IMAGE

RUN apt-get update && apt-get install -y git

RUN mkdir /app
WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install mlflow
RUN pip install -r requirements.txt